/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quarto;

/**
 *
 * @author mivip
 */
public class PlateauAff extends javax.swing.JFrame {

    /**
     * Creates new form PlateauAff
     */
    public PlateauAff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Case_00 = new javax.swing.JButton();
        Case_10 = new javax.swing.JButton();
        Case_20 = new javax.swing.JButton();
        Case_30 = new javax.swing.JButton();
        Case_01 = new javax.swing.JButton();
        Case_11 = new javax.swing.JButton();
        Case_21 = new javax.swing.JButton();
        Case_31 = new javax.swing.JButton();
        Case_02 = new javax.swing.JButton();
        Case_12 = new javax.swing.JButton();
        Case_22 = new javax.swing.JButton();
        Case_32 = new javax.swing.JButton();
        Case_03 = new javax.swing.JButton();
        Case_13 = new javax.swing.JButton();
        Case_23 = new javax.swing.JButton();
        Command_txt = new javax.swing.JLabel();
        List_Pieces_Restantes = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Case_33 = new javax.swing.JButton();
        Piece_0000 = new javax.swing.JButton();
        Piece_0001 = new javax.swing.JButton();
        Piece_0010 = new javax.swing.JButton();
        Piece_0011 = new javax.swing.JButton();
        Piece_0100 = new javax.swing.JButton();
        Piece_0101 = new javax.swing.JButton();
        Piece_0110 = new javax.swing.JButton();
        Piece_0111 = new javax.swing.JButton();
        Piece_1000 = new javax.swing.JButton();
        Piece_1001 = new javax.swing.JButton();
        Piece_1010 = new javax.swing.JButton();
        Piece_1100 = new javax.swing.JButton();
        Piece_1011 = new javax.swing.JButton();
        Piece_1101 = new javax.swing.JButton();
        Piece_1110 = new javax.swing.JButton();
        Piece_1111 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Case_00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tile.png"))); // NOI18N
        Case_00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_00ActionPerformed(evt);
            }
        });

        Case_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tile.png"))); // NOI18N
        Case_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_10ActionPerformed(evt);
            }
        });

        Case_20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tile.png"))); // NOI18N
        Case_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_20ActionPerformed(evt);
            }
        });

        Case_30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tile.png"))); // NOI18N
        Case_30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_30ActionPerformed(evt);
            }
        });

        Case_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tile.png"))); // NOI18N
        Case_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_01ActionPerformed(evt);
            }
        });

        Case_11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tile.png"))); // NOI18N
        Case_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_11ActionPerformed(evt);
            }
        });

        Case_21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_21ActionPerformed(evt);
            }
        });

        Case_31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_31ActionPerformed(evt);
            }
        });

        Case_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_02ActionPerformed(evt);
            }
        });

        Case_12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_12ActionPerformed(evt);
            }
        });

        Case_22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_22ActionPerformed(evt);
            }
        });

        Case_32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_32ActionPerformed(evt);
            }
        });

        Case_03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_03ActionPerformed(evt);
            }
        });

        Case_13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_13ActionPerformed(evt);
            }
        });

        Case_23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_23ActionPerformed(evt);
            }
        });

        Command_txt.setText("Message Interactif");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Piece0000", "Piece0001", "Piece0010", "Piece0011", "Piece0100", "Piece0101", "Piece0110", "Piece0111", "Piece1000", "Piece1001", "Piece1010", "Piece1100", "Piece1011", "Piece1110", "Piece1101", "Piece1111" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        List_Pieces_Restantes.setViewportView(jList1);

        Case_33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/tile.png"))); // NOI18N
        Case_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case_33ActionPerformed(evt);
            }
        });

        Piece_0000.setText("Piece 0000");

        Piece_0001.setText("Piece 0001");

        Piece_0010.setText("Piece 0010");

        Piece_0011.setText("Piece 0011");

        Piece_0100.setText("Piece 0100");

        Piece_0101.setText("Piece 0101");

        Piece_0110.setText("Piece 0110");

        Piece_0111.setText("Piece 0111");

        Piece_1000.setText("Piece 1000");

        Piece_1001.setText("Piece 1001");

        Piece_1010.setText("Piece 1010");

        Piece_1100.setText("Piece 1100");

        Piece_1011.setText("Piece 1011");

        Piece_1101.setText("Piece 1101");

        Piece_1110.setText("Piece 1110");
        Piece_1110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piece_1110ActionPerformed(evt);
            }
        });

        Piece_1111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quarto/rondblancgrandcreux.png"))); // NOI18N
        Piece_1111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Piece_1111ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Command_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Case_03)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Case_02)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Case_01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Case_00)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case_30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(List_Pieces_Restantes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Piece_0000)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_0001)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_0010)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Piece_0011))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Piece_0100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_0101)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_0110)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Piece_0111))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Piece_1000)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_1001)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_1010)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Piece_1100))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Piece_1011)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_1101)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Piece_1110)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Piece_1111)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Command_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Case_00)
                            .addComponent(Case_10)
                            .addComponent(Case_20)
                            .addComponent(Case_30))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Case_01)
                            .addComponent(Case_11)
                            .addComponent(Case_21)
                            .addComponent(Case_31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Case_02)
                            .addComponent(Case_12)
                            .addComponent(Case_22)
                            .addComponent(Case_32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Case_03)
                                .addComponent(Case_13)
                                .addComponent(Case_23))
                            .addComponent(Case_33)))
                    .addComponent(List_Pieces_Restantes, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Piece_0000)
                            .addComponent(Piece_0001)
                            .addComponent(Piece_0010)
                            .addComponent(Piece_0011))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Piece_0100)
                            .addComponent(Piece_0101)
                            .addComponent(Piece_0110)
                            .addComponent(Piece_0111))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Piece_1000)
                            .addComponent(Piece_1001)
                            .addComponent(Piece_1010)
                            .addComponent(Piece_1100))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Piece_1011)
                            .addComponent(Piece_1101)
                            .addComponent(Piece_1110)
                            .addComponent(Piece_1111))))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Case_00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_00ActionPerformed
        // TODO add your handling code here:
        Command_txt.setText("Coordonnées (0,0)");
    }//GEN-LAST:event_Case_00ActionPerformed

    private void Case_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_10ActionPerformed
        Command_txt.setText("Coordonnées (1,0)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_10ActionPerformed

    private void Case_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_20ActionPerformed
        // TODO add your handling code here:
        Command_txt.setText("Coordonnées (2,0)");
    }//GEN-LAST:event_Case_20ActionPerformed

    private void Case_30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_30ActionPerformed
        Command_txt.setText("Coordonnées (3,0)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_30ActionPerformed

    private void Case_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_01ActionPerformed
        Command_txt.setText("Coordonnées (0,1)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_01ActionPerformed

    private void Case_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_11ActionPerformed
        Command_txt.setText("Coordonnées (1,1)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_11ActionPerformed

    private void Case_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_21ActionPerformed
        Command_txt.setText("Coordonnées (2,1)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_21ActionPerformed

    private void Case_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_31ActionPerformed
        Command_txt.setText("Coordonnées (3,1)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_31ActionPerformed

    private void Case_02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_02ActionPerformed
        Command_txt.setText("Coordonnées (0,2)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_02ActionPerformed

    private void Case_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_12ActionPerformed
        Command_txt.setText("Coordonnées (1,2)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_12ActionPerformed

    private void Case_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_22ActionPerformed
        // TODO add your handling code here:
        Command_txt.setText("Coordonnées (2,2)");
    }//GEN-LAST:event_Case_22ActionPerformed

    private void Case_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_32ActionPerformed
        Command_txt.setText("Coordonnées (3,2)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_32ActionPerformed

    private void Case_03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_03ActionPerformed
        Command_txt.setText("Coordonnées (0,3)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_03ActionPerformed

    private void Case_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_13ActionPerformed
        Command_txt.setText("Coordonnées (1,3)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_13ActionPerformed

    private void Case_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_23ActionPerformed
        Command_txt.setText("Coordonnées (2,3)");
        // TODO add your handling code here:
    }//GEN-LAST:event_Case_23ActionPerformed

    private void Case_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case_33ActionPerformed
        // TODO add your handling code here:
        Command_txt.setText("Coordonnées (3,3)");
        Case_33.hide();
    }//GEN-LAST:event_Case_33ActionPerformed

    private void Piece_1110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piece_1110ActionPerformed
        // TODO add your handling code here:
        Command_txt.setText("Vous avez choisi la piece 1110\nAu tour de J[autre]");
        Piece_1110.hide();
    }//GEN-LAST:event_Piece_1110ActionPerformed

    private void Piece_1111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Piece_1111ActionPerformed
        Command_txt.setText("Vous avez choisi la piece 1111\nAu tour de J[autre]");
        Piece_1111.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_Piece_1111ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlateauAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlateauAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlateauAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlateauAff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlateauAff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Case_00;
    private javax.swing.JButton Case_01;
    private javax.swing.JButton Case_02;
    private javax.swing.JButton Case_03;
    private javax.swing.JButton Case_10;
    private javax.swing.JButton Case_11;
    private javax.swing.JButton Case_12;
    private javax.swing.JButton Case_13;
    private javax.swing.JButton Case_20;
    private javax.swing.JButton Case_21;
    private javax.swing.JButton Case_22;
    private javax.swing.JButton Case_23;
    private javax.swing.JButton Case_30;
    private javax.swing.JButton Case_31;
    private javax.swing.JButton Case_32;
    private javax.swing.JButton Case_33;
    private javax.swing.JLabel Command_txt;
    private javax.swing.JScrollPane List_Pieces_Restantes;
    private javax.swing.JButton Piece_0000;
    private javax.swing.JButton Piece_0001;
    private javax.swing.JButton Piece_0010;
    private javax.swing.JButton Piece_0011;
    private javax.swing.JButton Piece_0100;
    private javax.swing.JButton Piece_0101;
    private javax.swing.JButton Piece_0110;
    private javax.swing.JButton Piece_0111;
    private javax.swing.JButton Piece_1000;
    private javax.swing.JButton Piece_1001;
    private javax.swing.JButton Piece_1010;
    private javax.swing.JButton Piece_1011;
    private javax.swing.JButton Piece_1100;
    private javax.swing.JButton Piece_1101;
    private javax.swing.JButton Piece_1110;
    private javax.swing.JButton Piece_1111;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
